---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "Arc-Backstage-mono-repo"
  description: "Arc-Backstage-mono-repo"
  namespace: "Arc-Backstage-mono-repo"
  annotations:
    github.com/project-slug: Gayathri-V1342/Arc-Backstage-mono-repo
    backstage.io/techdocs-ref: dir:.

spec:
  type: service
  lifecycle: experimental
  owner: Gayathri-V1342
  dependsOn:
    - component:arc/terraform-aws-ref-arch-db
    - component:arc/terraform-aws-ref-arch-network
    - component:arc/terraform-aws-refarch-tags
    - component:arc/terraform-module-aws-bootstrap
    - component:arc/terraform-module-aws-eks
    - component:arc/terraform-k8s-app
