environment = "Arc-Backstage-mono-repo"
namespace   = "Arc-Backstage-mono-repo"
name        = "Arc-Backstage-mono-repo"
region      = "ap-south-1"
project_name = "Arc-Backstage-mono-repo"
db_type      = "Arc-Backstage-mono-repo"
